const bounties = [
  {
    title: 'FAQ Document',
    code: 'BA012301',
    date: 'Feb 1, 2023',
    proposer: 'Valdorff',
    amount: '53 RPL',
    value: '$38',
    details:
      'Clean answers to frequently asked questions, including block diagrams etc to improve upon what’s in /support template use',
    fineprint:
      'Answers must be provided in both article / doc page PR form; pot can be refreshed by GMC if it runs low - idea was $100/answer',
    status: 'Open',
    url: 'https://dao.rocketpool.net/t/january-2023-gmc-call-for-bounty-applications-deadline-is-january-15th/1336/12',
    linkTitle: 'View Details',
  },
  {
    title: 'Native Grafana docs',
    code: 'BA022305',
    date: 'April 3, 2023',
    proposer: 'jcrtp',
    amount: '10 RPL',
    value: '$47',
    details:
      'Add metrics collection and Grafana dashboard to the official Rocket Pool Node Operator guides documentation for Native Mode users.',
    fineprint: '',
    status: 'Open',
    url: 'https://dao.rocketpool.net/t/april-2023-gmc-call-for-bounty-applications-deadline-is-april-15th/1637/6',
    linkTitle: 'View Details',
  },
  {
    title: 'Node Operator FAQs doc',
    code: 'BA022306',
    date: 'April 3, 2023',
    proposer: 'jcrtp',
    amount: '2 RPL',
    value: '$47',
    details:
      'Complete the FAQs section for Node Operators in the guide documentation.',
    fineprint: '',
    status: 'Open',
    url: 'https://dao.rocketpool.net/t/april-2023-gmc-call-for-bounty-applications-deadline-is-april-15th/1637/7',
    linkTitle: 'View Details',
  },
  {
    title: 'Liquid Stakers FAQs doc',
    code: 'BA022307',
    date: 'April 3, 2023',
    proposer: 'jcrtp',
    amount: '2 RPL',
    value: '$47',
    details:
      'Complete the FAQs section for Liquid Stakers in the guide documentation.',
    fineprint: '',
    status: 'Open',
    url: 'https://dao.rocketpool.net/t/april-2023-gmc-call-for-bounty-applications-deadline-is-april-15th/1637/9',
    linkTitle: 'View Details',
  },
  {
    title: 'Support Notif. for Smartnode',
    code: 'BA022308',
    date: 'April 3, 2023',
    proposer: 'jcrtp',
    amount: '215 RPL',
    value: '$47',
    details: 'Add support for notifications to the Smartnode.',
    fineprint: '',
    status: 'Open',
    url: 'https://dao.rocketpool.net/t/april-2023-gmc-call-for-bounty-applications-deadline-is-april-15th/1637/10',
    linkTitle: 'View Details',
  },
  {
    title: 'RocketArb for Closes',
    code: 'BA022310',
    date: 'April 3, 2023',
    proposer: 'jcrtp',
    amount: '100 RPL',
    value: '$47',
    details:
      'Create a Smartnode addon for Rocketarb that supports arbitrage capture for both new minipool deposits and minipool closes / final distributions.',
    fineprint: '',
    status: 'Open',
    url: 'https://dao.rocketpool.net/t/april-2023-gmc-call-for-bounty-applications-deadline-is-april-15th/1637/12',
    linkTitle: 'View Details',
  },
  {
    title: 'Bounty Writing',
    code: 'BA032305',
    date: 'August 1, 2023',
    proposer: 'Valdorff',
    amount: '3 RPL per submission',
    value: '$30',
    details:
      'Provide a small “thank you” to bounty writers that write successful bounties (accepted and completed by someone else). The bounty bounty does not View Details to really small bounties (under 100 RPL).',
    fineprint: '',
    status: 'Open',
    url: 'https://dao.rocketpool.net/t/july-2023-gmc-call-for-bounty-applications-deadline-is-july-15th/1936/7',
    linkTitle: 'View Details',
  },
  {
    title: 'Treegen Testing Support',
    code: 'BA052301',
    date: 'October 27, 2023',
    proposer: 'Valdorff',
    amount: '130.44',
    value: '$23',
    details:
      'Creating an independent implementation of treegen, and supporting testing for each new tree spec.',
    fineprint: '',
    status: 'Open',
    url: 'https://dao.rocketpool.net/t/july-2023-gmc-call-for-bounty-applications-deadline-is-july-15th/1936/7',
    linkTitle: 'View Details',
  },
  {
    title: 'Improve LST Dashboard',
    code: 'BA052302',
    date: 'October 27, 2023',
    proposer: 'Valdorff',
    amount: '21.74',
    value: '$23',
    details:
      'Improve the LST comparison dashboard at https://dune.com/rp_community/lst-comparison.',
    fineprint: '',
    status: 'Open',
    url: 'https://dao.rocketpool.net/t/july-2023-gmc-call-for-bounty-applications-deadline-is-july-15th/1936/7',
    linkTitle: 'View Details',
  },
  {
    title: 'RPIP Review',
    code: 'BA062302',
    date: 'November 27, 2023',
    proposer: 'ShfRyn',
    amount: '192.31',
    value: '$26',
    details:
      'Contribute a reasonable impact towards the review or verification of a ratified RPIP.',
    fineprint: '',
    status: 'Open',
    url: 'https://dao.rocketpool.net/t/round-6-gmc-call-for-bounty-applications-deadline-is-november-11/2263/3',
    linkTitle: 'View Details',
  },
  {
    title: 'RP Scorecard',
    code: 'BA062304',
    date: 'November 27, 2023',
    proposer: 'Valdorff',
    amount: '576.92',
    value: '$26',
    details:
      'Improve the LST comparison dashboard at https://dune.com/rp_community/lst-comparison.',
    fineprint: '',
    status: 'Open',
    url: 'https://dao.rocketpool.net/t/round-6-gmc-call-for-bounty-applications-deadline-is-november-11/2263/5',
    linkTitle: 'View Details',
  },
];
