const bounties = [
  {
    title: 'FAQ Document',
    code: 'BA012301',
    date: 'Feb 1, 2023',
    proposer: 'Valdorff',
    amount: '53 RPL',
    value: '$38',
    details:
      'Clean answers to frequently asked questions, including block diagrams etc to improve upon what’s in /support template use',
    fineprint:
      'Answers must be provided in both article / doc page PR form; pot can be refreshed by GMC if it runs low - idea was $100/answer',
    status: 'Open',
    url: 'https://dao.rocketpool.net/t/january-2023-gmc-call-for-bounty-applications-deadline-is-january-15th/1336/12',
    linkTitle: 'Apply',
  },
  {
    title: 'Native Grafana docs',
    code: 'BA022304',
    date: 'April 3, 2023',
    proposer: 'jcrtp',
    amount: '10 RPL',
    value: '$47',
    details:
      'Add metrics collection and Grafana dashboard to the official Rocket Pool Node Operator guides documentation for Native Mode users.',
    fineprint: '',
    status: 'Open',
    url: 'https://dao.rocketpool.net/t/april-2023-gmc-call-for-bounty-applications-deadline-is-april-15th/1637/6',
    linkTitle: 'Apply',
  },
  {
    title: 'Node Operator FAQs doc',
    code: 'BA022306',
    date: 'April 3, 2023',
    proposer: 'jcrtp',
    amount: '2 RPL',
    value: '$47',
    details:
      'Complete the FAQs section for Node Operators in the guide documentation.',
    fineprint: '',
    status: 'Open',
    url: 'https://dao.rocketpool.net/t/april-2023-gmc-call-for-bounty-applications-deadline-is-april-15th/1637/7',
    linkTitle: 'Apply',
  },
  {
    title: 'Liquid Stakers FAQs doc',
    code: 'BA022307',
    date: 'April 3, 2023',
    proposer: 'jcrtp',
    amount: '2 RPL',
    value: '$47',
    details:
      'Complete the FAQs section for Liquid Stakers in the guide documentation.',
    fineprint: '',
    status: 'Open',
    url: 'https://dao.rocketpool.net/t/april-2023-gmc-call-for-bounty-applications-deadline-is-april-15th/1637/9',
    linkTitle: 'Apply',
  },
  {
    title: 'Support Notif. for Smartnode',
    code: 'BA022308',
    date: 'April 3, 2023',
    proposer: 'jcrtp',
    amount: '215 RPL',
    value: '$47',
    details: 'Add support for notifications to the Smartnode.',
    fineprint: '',
    status: 'Open',
    url: 'https://dao.rocketpool.net/t/april-2023-gmc-call-for-bounty-applications-deadline-is-april-15th/1637/10',
    linkTitle: 'Apply',
  },
  {
    title: 'RocketArb for Closes',
    code: 'BA022310',
    date: 'April 3, 2023',
    proposer: 'jcrtp',
    amount: '100 RPL',
    value: '$47',
    details:
      'Create a Smartnode addon for Rocketarb that supports arbitrage capture for both new minipool deposits and minipool closes / final distributions.',
    fineprint: '',
    status: 'Open',
    url: 'https://dao.rocketpool.net/t/april-2023-gmc-call-for-bounty-applications-deadline-is-april-15th/1637/12',
    linkTitle: 'Apply',
  },
  {
    title: 'Update RP documentation / website',
    code: 'BA032303',
    date: 'August 1, 2023',
    proposer: 'Valdorff',
    amount: '33.34 RPL',
    value: '$30',
    details:
      'This bounty is read through all RP documentation, as well as rocketpool.net, and find outright errors due to age. Things like references to the upcoming merge, active 5-20% commission, 15% default commission, etc, etc.',
    fineprint: '',
    status: 'Open',
    url: 'https://dao.rocketpool.net/t/july-2023-gmc-call-for-bounty-applications-deadline-is-july-15th/1936/4',
    linkTitle: 'Apply',
  },
  {
    title: 'MEV Theft Reporting',
    code: 'BA032304',
    date: 'August 1, 2023',
    proposer: 'Valdorff',
    amount: '583.34 RPL',
    value: '$30',
    details:
      'There is very little visibility into if MEV theft is happening, how frequently, how damaging, etc. We may not be able to get exact answers, but we should get close.',
    fineprint: '',
    status: 'Open',
    url: 'https://dao.rocketpool.net/t/july-2023-gmc-call-for-bounty-applications-deadline-is-july-15th/1936/5',
    linkTitle: 'Apply',
  },
  {
    title: 'Bounty Writing',
    code: 'BA032305',
    date: 'August 1, 2023',
    proposer: 'Valdorff',
    amount: '3 RPL per submission',
    value: '$30',
    details:
      'Provide a small “thank you” to bounty writers that write successful bounties (accepted and completed by someone else). The bounty bounty does not apply to really small bounties (under 100 RPL).',
    fineprint: '',
    status: 'Open',
    url: 'https://dao.rocketpool.net/t/july-2023-gmc-call-for-bounty-applications-deadline-is-july-15th/1936/7',
    linkTitle: 'Apply',
  },
  {
    title: 'GMC Administrator',
    code: 'BA022314',
    date: 'April 3, 2023',
    proposer: 'Calurduran',
    amount: '80 RPL',
    value: '$47',
    awardee: 'ShfRyn',
    dateOfAward: 'June 10, 2023',
    details:
      'Develop and expand the process and intricate details pertaining to a more comprehensive GMC administrator position.',
    fineprint: '',
    status: 'Closed',
    url: 'https://dao.rocketpool.net/t/april-2023-gmc-call-for-bounty-applications-deadline-is-april-15th/1637/16',
  },
  {
    title: 'Treegen Testing Support',
    code: 'BA022303',
    date: 'April 3, 2023',
    proposer: 'Valdorff',
    amount: '32 RPL',
    value: '$47',
    awardee: 'ramana',
    dateOfAward: 'August 16, 2023',
    details:
      'Creating an independent implementation of treegen, and supporting testing for each new tree spec.',
    fineprint: '',
    status: 'Closed',
    url: 'https://dao.rocketpool.net/t/april-2023-gmc-call-for-bounty-applications-deadline-is-april-15th/1637/4',
  },
  {
    title: 'Hybrid Grafana Docs',
    code: 'BA022304',
    date: 'April 3, 2023',
    proposer: 'jcrtp',
    amount: '10 RPL',
    value: '$47',
    awardee: 'Patches',
    dateOfAward: 'September 19, 2023',
    details:
      'Add metrics collection and Grafana dashboard to the official Rocket Pool Node Operator guides documentation for Hybrid Mode users.',
    fineprint: '',
    status: 'Closed',
    url: 'https://dao.rocketpool.net/t/april-2023-gmc-call-for-bounty-applications-deadline-is-april-15th/1637/5',
  },
];
